version: "3.7"
services: 
  worker-docx:
    build: .
    environment:
      - SECRET=encX990
      - PORT=3131
      - BASE_URL=/titan-forge/
    container_name: worker-docx  
    volumes: 
      - ./:/app/
    ports: 
      - "3131:3131"
    restart: unless-stopped
    command: bash -c 'npx nodemon app.js'